export interface TestCase {
  name: string;
  fixture: string;
  description: string;
  expectedExitCode?: number;
  expectTestPassed?: boolean;
  args?: string[];
}

export const testCases: TestCase[] = [
  {
    name: "simple-add",
    fixture: "tests/fixtures/arithmetic/simple-add.js",
    expectedExitCode: 12,
    description: "Simple addition: add(5, 7) should return 12",
  },
  {
    name: "simple-subtract",
    fixture: "tests/fixtures/arithmetic/simple-subtract.js",
    expectedExitCode: 7,
    description: "Simple subtraction: subtract(10, 3) should return 7",
  },
  {
    name: "simple-multiply",
    fixture: "tests/fixtures/arithmetic/simple-multiply.js",
    expectedExitCode: 42,
    description: "Simple multiplication: multiply(6, 7) should return 42",
  },
  {
    name: "simple-divide",
    fixture: "tests/fixtures/arithmetic/simple-divide.js",
    expectedExitCode: 5,
    description: "Simple division: divide(20, 4) should return 5",
  },
  {
    name: "simple-modulo",
    fixture: "tests/fixtures/arithmetic/simple-modulo.js",
    expectedExitCode: 2,
    description: "Simple modulo: modulo(17, 5) should return 2",
  },
  {
    name: "math-functions",
    fixture: "tests/fixtures/arithmetic/math-functions.js",
    expectedExitCode: 0,
    description: "Test all Math functions",
  },
  {
    name: "math-lib",
    fixture: "tests/fixtures/arithmetic/math-lib.js",
    expectedExitCode: 0,
    description: "Math library - exported functions",
  },
  {
    name: "nested-calls",
    fixture: "tests/fixtures/arithmetic/nested-calls.js",
    expectedExitCode: 17,
    description: "Nested function calls: calculate(4, 5) should return 17",
  },
  {
    name: "operator-precedence",
    fixture: "tests/fixtures/arithmetic/operator-precedence.js",
    expectedExitCode: 14,
    description: "Operator precedence: compute(2, 3, 4) should return 14",
  },
  {
    name: "complex-expression",
    fixture: "tests/fixtures/arithmetic/complex-expression.js",
    expectedExitCode: 32,
    description: "Complex expression: complex(5, 6, 10, 8) should return 32",
  },
  {
    name: "multiple-params",
    fixture: "tests/fixtures/arithmetic/multiple-params.js",
    expectedExitCode: 15,
    description: "Multiple parameters: sum(1, 2, 3, 4, 5) should return 15",
  },
  {
    name: "chained-calls",
    fixture: "tests/fixtures/arithmetic/chained-calls.js",
    expectedExitCode: 17,
    description: "Chained function calls: combined(2, 3, 4) should return 17",
  },
  {
    name: "if-else",
    fixture: "tests/fixtures/control-flow/if-else.js",
    expectedExitCode: 15,
    description: "If-else statement: max(15, 10) should return 15",
  },
  {
    name: "logical-operators",
    fixture: "tests/fixtures/logical/logical-operators.js",
    expectedExitCode: 5,
    description: "Logical operators: testOr(0, 5) should return 5",
  },
  {
    name: "nullish-coalescing",
    fixture: "tests/fixtures/logical/nullish-coalescing.ts",
    expectTestPassed: true,
    description: "Nullish coalescing operator (??) returns right operand only for null/undefined",
  },
  {
    name: "optional-chaining",
    fixture: "tests/fixtures/typescript/optional-chaining.ts",
    expectTestPassed: true,
    description: "Optional chaining (?.) returns undefined for null objects instead of crashing",
  },
  {
    name: "optional-chaining-types",
    fixture: "tests/fixtures/types/optional-chaining.ts",
    expectTestPassed: true,
    description: "Optional chaining on interfaces and strings returns correct values",
  },
  {
    name: "imports-main",
    fixture: "tests/fixtures/imports-exports/imports-main.js",
    expectedExitCode: 19,
    description: "Import/Export: multi-file compilation should work",
  },
  {
    name: "string-length",
    fixture: "tests/fixtures/strings/string-length.js",
    expectedExitCode: 5,
    description: "String .length property should return correct length",
  },
  {
    name: "string-split-length",
    fixture: "tests/fixtures/strings/string-split-length.ts",
    expectTestPassed: true,
    description:
      "README example: string.split() should work correctly and element.length should return proper lengths",
  },
  {
    name: "string-index",
    fixture: "tests/fixtures/strings/string-index.js",
    expectedExitCode: 66,
    description: "String indexing should return character code",
  },
  {
    name: "string-literal",
    fixture: "tests/fixtures/strings/string-literal.js",
    expectedExitCode: 4,
    description: "String literal in variable should work",
  },
  {
    name: "string-concat",
    fixture: "tests/fixtures/strings/string-concat.js",
    expectedExitCode: 10,
    description: "String concatenation should work",
  },
  {
    name: "string-substr",
    fixture: "tests/fixtures/strings/string-substr.js",
    expectedExitCode: 3,
    description: "String substr() method should work",
  },
  {
    name: "string-concat-method",
    fixture: "tests/fixtures/strings/string-concat-method.js",
    expectedExitCode: 11,
    description: "String concat() method should work",
  },
  {
    name: "string-repeat",
    fixture: "tests/fixtures/strings/string-repeat.js",
    expectedExitCode: 6,
    description: "String repeat() method should work",
  },
  {
    name: "string-padstart",
    fixture: "tests/fixtures/strings/string-padstart.js",
    expectedExitCode: 3,
    description: "String padStart() method should work",
  },
  {
    name: "process-argv",
    fixture: "tests/fixtures/builtins/process-argv-test.ts",
    expectTestPassed: true,
    description: "process.argv should provide command line arguments",
    args: ["testarg"],
  },
  {
    name: "process-argv-multi",
    fixture: "tests/fixtures/builtins/process-argv-multi.ts",
    expectTestPassed: true,
    description:
      "process.argv should handle multiple arguments and process.argv0 should be non-empty",
    args: ["hello", "world", "42"],
  },
  {
    name: "fs-readFileSync",
    fixture: "tests/fixtures/builtins/fs-readfile-test.ts",
    expectTestPassed: true,
    description: "fs.readFileSync should read file contents correctly",
  },
  {
    name: "word-count",
    fixture: "tests/fixtures/builtins/word-count-test.ts",
    expectTestPassed: true,
    description: "Word counting with for loops, split, and file reading",
  },
  {
    name: "console-log",
    fixture: "tests/fixtures/builtins/console-log.js",
    expectTestPassed: true,
    description: "console.log and console.error should output correctly",
  },
  {
    name: "console-log-array",
    fixture: "tests/fixtures/builtins/console-log-array.ts",
    expectTestPassed: true,
    description: "console.log should print arrays correctly",
  },
  {
    name: "console-multi-arg",
    fixture: "tests/fixtures/builtins/console-multi-arg.ts",
    expectTestPassed: true,
    description: "console.log should handle multiple comma-separated arguments",
  },
  {
    name: "parseint",
    fixture: "tests/fixtures/builtins/parseint.js",
    expectTestPassed: true,
    description: "parseInt should parse numbers with different radixes",
  },
  {
    name: "argv-debug",
    fixture: "tests/fixtures/builtins/argv-debug.ts",
    expectedExitCode: 0,
    description: "Debug process.argv",
  },
  {
    name: "argv-simple",
    fixture: "tests/fixtures/builtins/argv-simple.ts",
    expectedExitCode: 0,
    description: "Test argv with no user arguments",
  },
  {
    name: "fs-readFileSync-simple",
    fixture: "tests/fixtures/builtins/fs-readFileSync.js",
    expectedExitCode: 0,
    description: "fs.readFileSync basic test",
  },
  {
    name: "process-argv-simple",
    fixture: "tests/fixtures/builtins/process-argv.js",
    expectedExitCode: 0,
    description: "process.argv basic test",
  },
  {
    name: "array-includes",
    fixture: "tests/fixtures/arrays/array-includes-test.js",
    expectTestPassed: true,
    description: "Array .includes() should find elements correctly",
  },
  {
    name: "array-pop",
    fixture: "tests/fixtures/arrays/array-pop-test.js",
    expectTestPassed: true,
    description: "Array .pop() should remove and return last element",
  },
  {
    name: "array-methods",
    fixture: "tests/fixtures/arrays/array-methods.js",
    expectedExitCode: 0,
    description: "Array methods (pop, includes) should work",
  },
  {
    name: "string-array-concat",
    fixture: "tests/fixtures/arrays/string-array-concat.js",
    expectedExitCode: 0,
    description: "String array concatenation should work",
  },
  {
    name: "string-array-index",
    fixture: "tests/fixtures/arrays/string-array-index.js",
    expectedExitCode: 0,
    description: "String array indexing should work",
  },
  {
    name: "string-trim",
    fixture: "tests/fixtures/strings/string-trim-simple.ts",
    expectTestPassed: true,
    description: "String .trim() should remove leading and trailing whitespace",
  },
  {
    name: "string-methods",
    fixture: "tests/fixtures/strings/string-methods.js",
    expectedExitCode: 0,
    description: "Test new string methods: trim, indexOf, includes, slice",
  },
  {
    name: "simple-if",
    fixture: "tests/fixtures/control-flow/simple-if.ts",
    expectTestPassed: true,
    description: "Simple if statement should work",
  },
  {
    name: "ternary-complex",
    fixture: "tests/fixtures/control-flow/ternary-complex.js",
    expectTestPassed: true,
    description: "Nested ternary expressions should work",
  },
  {
    name: "ternary-nested",
    fixture: "tests/fixtures/control-flow/ternary-nested.js",
    expectTestPassed: true,
    description: "Deeply nested ternary expressions should work",
  },
  {
    name: "if-only",
    fixture: "tests/fixtures/control-flow/if-only.js",
    expectTestPassed: true,
    description: "If statement without else should work",
  },
  {
    name: "for-of-comprehensive",
    fixture: "tests/fixtures/control-flow/for-of-comprehensive.ts",
    expectTestPassed: true,
    description: "for...of loops over numeric arrays, string arrays, and with break",
  },
  {
    name: "string-length-check",
    fixture: "tests/fixtures/strings/string-length-check.ts",
    expectTestPassed: true,
    description: "String length comparisons should work",
  },
  {
    name: "string-array-basic",
    fixture: "tests/fixtures/arrays/string-array-basic.js",
    expectTestPassed: true,
    description: "String array creation and access should work",
  },
  {
    name: "regex-test",
    fixture: "tests/fixtures/regex/regex-test.js",
    expectedExitCode: 1,
    description: "Regex test() method should work",
  },
  {
    name: "regex-constructor",
    fixture: "tests/fixtures/regex/regex-constructor.ts",
    expectTestPassed: true,
    description: "new RegExp() constructor with flags (i, m) and dynamic patterns",
  },
  {
    name: "regex-exec",
    fixture: "tests/fixtures/regex/regex-exec.ts",
    expectTestPassed: true,
    description: "RegExp.exec() with literal, variable, and new RegExp patterns",
  },
  {
    name: "fs-readdirSync",
    fixture: "tests/fixtures/builtins/fs-readdir.ts",
    expectTestPassed: true,
    description: "fs.readdirSync should list directory entries",
  },
  {
    name: "fs-statSync",
    fixture: "tests/fixtures/builtins/fs-stat.ts",
    expectTestPassed: true,
    description: "fs.statSync should return file/directory metadata",
  },
  {
    name: "array-literal",
    fixture: "tests/fixtures/arrays/array-literal.js",
    expectedExitCode: 3,
    description: "Array literal and .length should work",
  },
  {
    name: "array-index",
    fixture: "tests/fixtures/arrays/array-index.js",
    expectedExitCode: 20,
    description: "Array indexing should work",
  },
  {
    name: "array-push",
    fixture: "tests/fixtures/arrays/array-push.js",
    expectedExitCode: 4,
    description: "Array .push() should add element and return new length",
  },
  {
    name: "array-find",
    fixture: "tests/fixtures/arrays/array-find.js",
    expectedExitCode: 3,
    description: "Array .find() should return first matching element",
  },
  {
    name: "array-some",
    fixture: "tests/fixtures/arrays/array-some.js",
    expectedExitCode: 1,
    description: "Array .some() should return 1 if any element matches",
  },
  {
    name: "array-filter",
    fixture: "tests/fixtures/arrays/array-filter.js",
    expectedExitCode: 3,
    description: "Array .filter() should return new array with matching elements",
  },
  {
    name: "array-foreach",
    fixture: "tests/fixtures/arrays/array-foreach.js",
    expectedExitCode: 10,
    description: "Array .forEach() should call function for each element",
  },
  {
    name: "string-array-foreach",
    fixture: "tests/fixtures/arrays/string-array-foreach.ts",
    expectTestPassed: true,
    description: "forEach on string[] should pass string elements to callback",
  },
  {
    name: "array-slice",
    fixture: "tests/fixtures/arrays/array-slice.ts",
    expectTestPassed: true,
    description: "Array .slice() should return a new array with selected elements",
  },
  {
    name: "object-literal",
    fixture: "tests/fixtures/objects/object-literal.js",
    expectedExitCode: 30,
    description: "Object literal and property access should work",
  },
  {
    name: "object-nested",
    fixture: "tests/fixtures/objects/object-nested.js",
    expectedExitCode: 12,
    description: "Object with complex property expressions should work",
  },
  {
    name: "object-return",
    fixture: "tests/fixtures/objects/object-return.js",
    expectedExitCode: 42,
    description: "Returning object property should work",
  },
  {
    name: "object-literal-access",
    fixture: "tests/fixtures/objects/object-literal-access.js",
    expectedExitCode: 10,
    description: "Property access on object literal should work",
  },
  {
    name: "object-keys",
    fixture: "tests/fixtures/builtins/object-keys.ts",
    expectTestPassed: true,
    description: "Object.keys() should return field names of typed objects",
  },
  {
    name: "typeof",
    fixture: "tests/fixtures/builtins/typeof.ts",
    expectTestPassed: true,
    description: "typeof operator should return correct type strings",
  },
  {
    name: "object-method",
    fixture: "tests/fixtures/objects/object-method.js",
    expectedExitCode: 12,
    description: "Object method call should work",
  },
  {
    name: "class-basic",
    fixture: "tests/fixtures/classes/class-basic.js",
    expectedExitCode: 10,
    description: "Class with constructor, methods, and this should work",
  },
  {
    name: "class-field-new",
    fixture: "tests/fixtures/classes/class-field-new.ts",
    expectTestPassed: true,
    description: "Class field initialization with constructors works correctly",
  },
  {
    name: "while-loop",
    fixture: "tests/fixtures/control-flow/while-loop.js",
    expectedExitCode: 15,
    description: "While loop should sum numbers from 5 to 1",
  },
  {
    name: "for-loop",
    fixture: "tests/fixtures/control-flow/for-loop.js",
    expectedExitCode: 55,
    description: "For loop should sum numbers from 1 to 10",
  },
  {
    name: "loop-break",
    fixture: "tests/fixtures/control-flow/loop-break.js",
    expectedExitCode: 43,
    description: "Break statement should exit loop early",
  },
  {
    name: "loop-continue",
    fixture: "tests/fixtures/control-flow/loop-continue.js",
    expectedExitCode: 12,
    description: "Continue statement should skip to next iteration",
  },
  {
    name: "map-basic",
    fixture: "tests/fixtures/data-structures/map-basic.ts",
    expectTestPassed: true,
    description: "Map with set/get operations should work",
  },
  {
    name: "set-basic",
    fixture: "tests/fixtures/data-structures/set-basic.ts",
    expectedExitCode: 1,
    description: "Set with add/has operations should work",
  },
  {
    name: "set-overflow",
    fixture: "tests/fixtures/data-structures/set-overflow.ts",
    expectTestPassed: true,
    description: "Set with >4 elements should grow buffer correctly",
  },
  {
    name: "string-set-overflow",
    fixture: "tests/fixtures/data-structures/string-set-overflow.ts",
    expectTestPassed: true,
    description: "StringSet with >4 elements should grow buffer correctly",
  },
  {
    name: "set-type-args",
    fixture: "tests/fixtures/collections/set-type-args.ts",
    expectTestPassed: true,
    description: "Set with explicit type args should infer correct types",
  },
  {
    name: "strict-equality",
    fixture: "tests/fixtures/comparisons/strict-equality.js",
    expectedExitCode: 15,
    description: "Strict equality (===) and inequality (!==) operators should work",
  },
  {
    name: "ternary",
    fixture: "tests/fixtures/control-flow/ternary.js",
    expectedExitCode: 15,
    description: "Ternary operator (? :) should work",
  },
  {
    name: "function-expression",
    fixture: "tests/fixtures/functions/function-expression.js",
    expectedExitCode: 0,
    description: "Function expressions in array methods should work",
  },
  {
    name: "return-boolean",
    fixture: "tests/fixtures/edge-cases/return-boolean.js",
    expectedExitCode: 1,
    description: "Boolean literals (true/false) should work",
  },
  {
    name: "shebang",
    fixture: "tests/fixtures/edge-cases/shebang.js",
    expectedExitCode: 0,
    description: "Shebang line should be handled correctly",
  },
  {
    name: "bitwise-operators",
    fixture: "tests/fixtures/bitwise/bitwise-operators.js",
    expectedExitCode: 0,
    description: "Test all bitwise operators",
  },
  {
    name: "throw-simple",
    fixture: "tests/fixtures/error-handling/throw-simple.js",
    expectedExitCode: 0,
    description: "Simple throw statement",
  },
  {
    name: "try-catch-throw",
    fixture: "tests/fixtures/error-handling/try-catch-throw.js",
    expectTestPassed: true,
    description: "Try-catch-throw flow",
  },
  {
    name: "try-catch-finally",
    fixture: "tests/fixtures/error-handling/try-catch-finally.js",
    expectTestPassed: true,
    description: "Finally blocks run with and without throw",
  },
  {
    name: "try-catch-nested",
    fixture: "tests/fixtures/error-handling/try-catch-nested.js",
    expectTestPassed: true,
    description: "Nested try-catch blocks handle exceptions at correct level",
  },
  {
    name: "try-catch-rethrow",
    fixture: "tests/fixtures/error-handling/try-catch-rethrow.js",
    expectTestPassed: true,
    description: "Throw inside catch propagates to outer try-catch",
  },
  {
    name: "http-simple-test",
    fixture: "tests/fixtures/network/http-simple-test.ts",
    expectedExitCode: 0,
    description: "Simplified HTTP handler test",
  },
  {
    name: "tcp-echo-server",
    fixture: "tests/fixtures/network/tcp-echo-server.ts",
    expectedExitCode: 0,
    description: "TCP Echo Server - Functional style without interface returns",
  },
  {
    name: "ws-server-basic",
    fixture: "tests/fixtures/websocket/ws-server-basic.ts",
    expectTestPassed: true,
    description: "WebSocket server basic compilation test",
  },
  {
    name: "typescript-struct",
    fixture: "tests/fixtures/typescript/typescript-struct.ts",
    expectedExitCode: 7,
    description: "TypeScript interface with struct property access should work",
  },
  {
    name: "array-init-safe",
    fixture: "tests/fixtures/arrays/array-init-safe.ts",
    expectedExitCode: 10,
    description: "Array initialization should be zero-initialized to prevent crashes on iteration",
  },
  // Regression tests for float/double conversion edge cases
  {
    name: "array-index-float-conversion",
    fixture: "tests/fixtures/edge-cases/array-index-float-conversion.js",
    expectedExitCode: 30,
    description: "Array indexing with float values should convert to int (regression test)",
  },
  {
    name: "string-length-arithmetic",
    fixture: "tests/fixtures/edge-cases/string-length-arithmetic.js",
    expectedExitCode: 10,
    description: "String.length in arithmetic should convert i32 to double (regression test)",
  },
  {
    name: "array-length-comparison",
    fixture: "tests/fixtures/edge-cases/array-length-comparison.js",
    expectedExitCode: 42,
    description: "Array.length in comparisons should convert properly (regression test)",
  },
  {
    name: "array-length-multiplication",
    fixture: "tests/fixtures/edge-cases/array-indexof-arithmetic.js",
    expectedExitCode: 20,
    description: "Array.length in multiplication should convert i32 to double (regression test)",
  },
  {
    name: "bitwise-float-conversion",
    fixture: "tests/fixtures/edge-cases/bitwise-float-conversion.js",
    expectedExitCode: 8,
    description: "Bitwise operations with floats should convert to integers (regression test)",
  },
  {
    name: "object-destructure",
    fixture: "tests/fixtures/destructuring/object-destructure.ts",
    expectTestPassed: true,
    description: "Object destructuring const { x, y } = obj should work",
  },
  {
    name: "object-destructure-rename",
    fixture: "tests/fixtures/destructuring/object-destructure-rename.ts",
    expectTestPassed: true,
    description: "Object destructuring with renaming const { host: h } = obj should work",
  },
  {
    name: "array-destructure",
    fixture: "tests/fixtures/destructuring/array-destructure.ts",
    expectTestPassed: true,
    description: "Array destructuring const [a, b, c] = arr should work",
  },
  {
    name: "array-reduce",
    fixture: "tests/fixtures/arrays/array-reduce.ts",
    expectTestPassed: true,
    description: "Array.reduce() with named function, arrow function, and no initial value",
  },
  {
    name: "array-spread",
    fixture: "tests/fixtures/arrays/array-spread.ts",
    expectTestPassed: true,
    description: "Spread operator in array literals [...arr, x] should work",
  },
  {
    name: "array-index-assign",
    fixture: "tests/fixtures/arrays/array-index-assign.ts",
    expectTestPassed: true,
    description: "Array element assignment arr[i] = value with computed indices",
  },
  {
    name: "object-array-assignment",
    fixture: "tests/fixtures/arrays/object-array-assignment.ts",
    expectTestPassed: true,
    description: "Object array element assignment items[i] = { ... }",
  },
  {
    name: "rest-params",
    fixture: "tests/fixtures/functions/rest-params.ts",
    expectTestPassed: true,
    description: "Rest parameters function(...args) with spread call syntax should work",
  },
  {
    name: "user-main-function",
    fixture: "tests/fixtures/functions/user-main-function.ts",
    expectTestPassed: true,
    description: "User function named main() should not conflict with C entry point",
  },
  {
    name: "string-replaceall",
    fixture: "tests/fixtures/strings/string-replaceall.ts",
    expectTestPassed: true,
    description: "String.replaceAll() should replace all occurrences of a substring",
  },
  {
    name: "string-trim-variants",
    fixture: "tests/fixtures/strings/string-trim-variants.ts",
    expectTestPassed: true,
    description: "String.trimStart() and trimEnd() should trim whitespace from one side",
  },
  {
    name: "array-isarray",
    fixture: "tests/fixtures/arrays/array-isarray.ts",
    expectTestPassed: true,
    description: "Array.isArray() should return true for arrays and false for non-arrays",
  },
  {
    name: "process-platform",
    fixture: "tests/fixtures/builtins/process-platform.ts",
    expectTestPassed: true,
    description: "process.platform should return the current platform string",
  },
  {
    name: "number-methods",
    fixture: "tests/fixtures/builtins/number-methods.ts",
    expectTestPassed: true,
    description: "Number.isFinite(), Number.isNaN(), Number.isInteger(), Number.toString()",
  },
  {
    name: "process-stdout-write",
    fixture: "tests/fixtures/builtins/process-stdout-write.ts",
    expectTestPassed: true,
    description: "process.stdout.write() should output without trailing newline",
  },
  {
    name: "object-values-entries",
    fixture: "tests/fixtures/builtins/object-values-entries.ts",
    expectTestPassed: true,
    description: "Object.values() and Object.entries() should return object field values",
  },
  {
    name: "process-env",
    fixture: "tests/fixtures/builtins/process-env.ts",
    expectTestPassed: true,
    description: "process.env should read environment variables via getenv()",
  },
  {
    name: "process-properties",
    fixture: "tests/fixtures/builtins/process-properties.ts",
    expectTestPassed: true,
    description: "process.arch, version, pid, ppid, execPath, argv0",
  },
  {
    name: "process-methods",
    fixture: "tests/fixtures/builtins/process-methods.ts",
    expectTestPassed: true,
    description: "process.getuid, getgid, geteuid, getegid, uptime, chdir, kill",
  },
  {
    name: "tty-isatty",
    fixture: "tests/fixtures/builtins/tty-isatty.ts",
    expectTestPassed: true,
    description: "tty.isatty() syscall for terminal detection",
  },
  {
    name: "crypto",
    fixture: "tests/fixtures/builtins/crypto-test.ts",
    expectTestPassed: true,
    description: "crypto.sha256, md5, sha512, randomBytes via OpenSSL",
  },
  {
    name: "sqlite",
    fixture: "tests/fixtures/builtins/sqlite-test.ts",
    expectTestPassed: true,
    description: "sqlite.open, exec, get, all, close via libsqlite3",
  },
  {
    name: "large-numbers",
    fixture: "tests/fixtures/math/large-numbers.ts",
    expectTestPassed: true,
    description: "large integer literals beyond i32 range and big arithmetic",
  },
  {
    name: "stable-struct",
    fixture: "tests/fixtures/interfaces/stable-struct.ts",
    expectedExitCode: 0,
    description: "Interface struct creation, passing, and returning should work",
  },
  {
    name: "type-assertion-named",
    fixture: "tests/fixtures/types/type-assertion-named.ts",
    expectTestPassed: true,
    description: "Named and inline type assertions should produce identical results",
  },
  {
    name: "nested-interface-access",
    fixture: "tests/fixtures/interfaces/nested-interface-access.ts",
    expectTestPassed: true,
    description: "Chained interface field access (a.b.c) should work",
  },
  {
    name: "interface-array-mutation",
    fixture: "tests/fixtures/arrays/interface-array-mutation.ts",
    expectTestPassed: true,
    description:
      "Mutating fields of interface objects in arrays (arr[i].field = value) should work",
  },
  {
    name: "class-field-object-array",
    fixture: "tests/fixtures/arrays/class-field-object-array.ts",
    expectTestPassed: true,
    description: "Class field object arrays (this.items[i].field read/write) should work",
  },
  {
    name: "string-builder",
    fixture: "tests/fixtures/strings/string-builder.ts",
    expectTestPassed: true,
    description: "String builder optimization for s = s + x pattern should produce correct results",
  },
  {
    name: "string-builder-loop",
    fixture: "tests/fixtures/strings/string-builder-loop.ts",
    expectTestPassed: true,
    description: "String builder with let re-declaration inside a loop should not segfault",
  },
  {
    name: "string-concat-assign",
    fixture: "tests/fixtures/strings/string-concat-assign.ts",
    expectTestPassed: true,
    description: "String += accumulation in a loop should produce correct length",
  },
  {
    name: "string-lastindexof",
    fixture: "tests/fixtures/strings/string-lastindexof.ts",
    expectTestPassed: true,
    description: "String.lastIndexOf() should find last occurrence of substring",
  },
  {
    name: "test-runner-basic",
    fixture: "tests/fixtures/test-runner/basic.ts",
    expectTestPassed: true,
    description: "Built-in test runner with test() and assert.* (all pass)",
  },
  {
    name: "test-runner-failures",
    fixture: "tests/fixtures/test-runner/failures.ts",
    expectedExitCode: 1,
    description: "Built-in test runner with mixed pass/fail (exit code 1)",
  },
  {
    name: "test-runner-deep-equal",
    fixture: "tests/fixtures/test-runner/deep-equal.ts",
    expectTestPassed: true,
    description: "assert.deepEqual() for number and string arrays",
  },
  {
    name: "test-runner-describe",
    fixture: "tests/fixtures/test-runner/describe.ts",
    expectTestPassed: true,
    description: "describe() blocks for grouping tests with indentation",
  },
  {
    name: "uint8array-basic",
    fixture: "tests/fixtures/typed-arrays/uint8array-basic.ts",
    expectTestPassed: true,
    description: "Uint8Array constructor, index read/write, and .length",
  },
  {
    name: "argparse-subcommand-basic",
    fixture: "tests/fixtures/argparse/subcommand-basic.ts",
    expectTestPassed: true,
    description: "ArgumentParser subcommand dispatch with flags and options",
    args: ["build", "hello.ts", "-o", "out"],
  },
  {
    name: "argparse-double-dash",
    fixture: "tests/fixtures/argparse/double-dash.ts",
    expectTestPassed: true,
    description: "ArgumentParser -- separator puts remaining args into restArgs",
    args: ["run", "hello.ts", "--", "arg1", "arg2"],
  },
  {
    name: "argparse-equals-syntax",
    fixture: "tests/fixtures/argparse/equals-syntax.ts",
    expectTestPassed: true,
    description: "ArgumentParser --key=value option syntax",
    args: ["--target-cpu=x86-64", "build", "hello.ts"],
  },
  {
    name: "embed-file",
    fixture: "tests/fixtures/builtins/embed-file.ts",
    expectTestPassed: true,
    description: "ChadScript.embedFile() embeds file content at compile time",
  },
  {
    name: "embed-dir",
    fixture: "tests/fixtures/builtins/embed-dir.ts",
    expectTestPassed: true,
    description: "ChadScript.embedDir() + getEmbeddedFile() for directory embedding",
  },
  {
    name: "math-trunc",
    fixture: "tests/fixtures/math/math-trunc.ts",
    expectTestPassed: true,
    description: "Math.trunc() truncates decimal part",
  },
  {
    name: "path-extname",
    fixture: "tests/fixtures/builtins/path-extname.ts",
    expectTestPassed: true,
    description: "path.extname() returns file extension",
  },
  {
    name: "path-isabsolute",
    fixture: "tests/fixtures/builtins/path-isabsolute.ts",
    expectTestPassed: true,
    description: "path.isAbsolute() checks for absolute paths",
  },
  {
    name: "path-normalize",
    fixture: "tests/fixtures/builtins/path-normalize.ts",
    expectTestPassed: true,
    description: "path.normalize() and path.sep",
  },
  {
    name: "path-relative",
    fixture: "tests/fixtures/builtins/path-relative.ts",
    expectTestPassed: true,
    description: "path.relative() returns relative path between two paths",
  },
  {
    name: "path-parse",
    fixture: "tests/fixtures/builtins/path-parse.ts",
    expectTestPassed: true,
    description: "path.parse() decomposes path into root/dir/base/name/ext",
  },
  {
    name: "date-instance",
    fixture: "tests/fixtures/builtins/date-instance.ts",
    expectTestPassed: true,
    description: "new Date() constructor and instance methods",
  },
  {
    name: "promise-allsettled",
    fixture: "tests/fixtures/builtins/promise-allsettled.ts",
    expectTestPassed: true,
    description: "Promise.allSettled() resolves even when some promises reject",
  },
  {
    name: "promise-any",
    fixture: "tests/fixtures/builtins/promise-any.ts",
    expectTestPassed: true,
    description: "Promise.any() resolves with first fulfilled value",
  },
  {
    name: "promise-finally",
    fixture: "tests/fixtures/builtins/promise-finally.ts",
    expectTestPassed: true,
    description: "promise.finally() runs callback and propagates value",
  },
  {
    name: "math-random",
    fixture: "tests/fixtures/math/math-random.ts",
    expectTestPassed: true,
    description: "Math.random() returns values in [0, 1)",
  },
  {
    name: "math-sign",
    fixture: "tests/fixtures/math/math-sign.ts",
    expectTestPassed: true,
    description: "Math.sign() returns -1, 0, or 1",
  },
  {
    name: "math-trig",
    fixture: "tests/fixtures/math/math-trig.ts",
    expectTestPassed: true,
    description: "Math.log(), Math.sin(), Math.cos() trigonometric functions",
  },
  {
    name: "string-padend",
    fixture: "tests/fixtures/strings/string-padend.ts",
    expectTestPassed: true,
    description: "String.padEnd() pads end of string",
  },
  {
    name: "set-delete",
    fixture: "tests/fixtures/data-structures/set-delete.ts",
    expectTestPassed: true,
    description: "Set.delete() removes elements from number and string sets",
  },
  {
    name: "fs-rename",
    fixture: "tests/fixtures/builtins/fs-rename.ts",
    expectTestPassed: true,
    description: "fs.renameSync() renames files",
  },
  {
    name: "fs-copyfile",
    fixture: "tests/fixtures/builtins/fs-copyfile.ts",
    expectTestPassed: true,
    description: "fs.copyFileSync() copies file contents",
  },
  {
    name: "fs-readfile-async",
    fixture: "tests/fixtures/builtins/fs-readfile-async.ts",
    expectTestPassed: true,
    description: "fs.readFile() async reads file contents",
  },
  {
    name: "fs-writefile-async",
    fixture: "tests/fixtures/builtins/fs-writefile-async.ts",
    expectTestPassed: true,
    description: "fs.writeFile() async writes file contents",
  },
  {
    name: "crypto-uuid",
    fixture: "tests/fixtures/builtins/crypto-uuid.ts",
    expectTestPassed: true,
    description: "crypto.randomUUID() generates valid v4 UUIDs",
  },
  {
    name: "console-time",
    fixture: "tests/fixtures/builtins/console-time.ts",
    expectTestPassed: true,
    description: "console.time() and console.timeEnd() measure elapsed time",
  },
  {
    name: "array-reverse",
    fixture: "tests/fixtures/arrays/array-reverse.ts",
    expectTestPassed: true,
    description: "Array.reverse() reverses arrays in-place",
  },
  {
    name: "array-indexof",
    fixture: "tests/fixtures/arrays/array-indexof.ts",
    expectTestPassed: true,
    description: "Array.indexOf() finds element index in arrays",
  },
  {
    name: "array-findindex",
    fixture: "tests/fixtures/arrays/array-findindex.ts",
    expectTestPassed: true,
    description: "Array.findIndex() finds index by predicate",
  },
  {
    name: "array-shift-unshift",
    fixture: "tests/fixtures/arrays/array-shift-unshift.ts",
    expectTestPassed: true,
    description: "Array.shift() and Array.unshift() modify array start",
  },
  {
    name: "array-sort",
    fixture: "tests/fixtures/arrays/array-sort.ts",
    expectTestPassed: true,
    description: "Array.sort() sorts arrays with default and custom comparators",
  },
  {
    name: "array-splice",
    fixture: "tests/fixtures/arrays/array-splice.ts",
    expectTestPassed: true,
    description: "Array.splice() removes elements and returns removed array",
  },
  {
    name: "cp-execsync",
    fixture: "tests/fixtures/builtins/cp-execsync.ts",
    expectTestPassed: true,
    description: "child_process.execSync() runs command and returns stdout",
  },
  {
    name: "cp-bare-execsync",
    fixture: "tests/fixtures/builtins/cp-bare-execsync.ts",
    expectTestPassed: true,
    description: "bare execSync() works without child_process prefix",
  },
  {
    name: "cp-spawnsync",
    fixture: "tests/fixtures/builtins/cp-spawnsync.ts",
    expectTestPassed: true,
    description: "child_process.spawnSync() with args returns stdout/stderr/status",
  },
  {
    name: "cp-spawnsync-shell",
    fixture: "tests/fixtures/builtins/cp-spawnsync-shell.ts",
    expectTestPassed: true,
    description: "child_process.spawnSync() shell mode with no args array",
  },
  {
    name: "cp-exec-async",
    fixture: "tests/fixtures/builtins/cp-exec-async.ts",
    expectTestPassed: true,
    description: "child_process.exec() async returns Promise with stdout/status",
  },
];
