// Regenerates the benchmark table on the docs site (docs/generated/benchmarks.md and
// docs/generated/benchmarks.json) by running scripts/bench.ts, which checks that ChadScript,
// Node and Rust print identical output before timing anything. The machine, toolchain versions
// and date are recorded with the numbers, because a table without them is not reproducible.
//
//   bun run docs/scripts/bench-page.ts                 # run the benchmarks (slow), then write
//   bun run docs/scripts/bench-page.ts --from r.json   # reuse a `bench.ts --json` result file

import { execFileSync } from "node:child_process";
import { mkdtempSync, readFileSync, writeFileSync } from "node:fs";
import { cpus, platform, arch, release, tmpdir } from "node:os";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

interface Timing {
  label: string;
  ms: number;
}
interface BenchResult {
  name: string;
  timings: Timing[] | null;
  note: string | null;
}
interface BenchFile {
  runs: number;
  results: BenchResult[];
}

const repo = join(dirname(fileURLToPath(import.meta.url)), "..", "..");

function version(cmd: string, args: string[]): string {
  try {
    return execFileSync(cmd, args, { encoding: "utf8" }).split("\n")[0]!.trim();
  } catch {
    return "unavailable";
  }
}

function osName(): string {
  if (platform() === "darwin") return `macOS ${version("sw_vers", ["-productVersion"])}`;
  return `${platform()} ${release()}`;
}

function fmt(ms: number): string {
  return ms >= 1000 ? `${(ms / 1000).toFixed(2)} s` : `${Math.round(ms)} ms`;
}

const argv = process.argv.slice(2);
const fromAt = argv.indexOf("--from");
let resultPath: string;
if (fromAt >= 0) {
  resultPath = argv[fromAt + 1] ?? "";
  if (resultPath === "") throw new Error("--from needs a file path");
} else {
  resultPath = join(mkdtempSync(join(tmpdir(), "chad-bench-")), "bench.json");
  execFileSync("bun", ["run", join(repo, "scripts", "bench.ts"), "--json", resultPath], {
    stdio: "inherit",
  });
}
const data = JSON.parse(readFileSync(resultPath, "utf8")) as BenchFile;

const machine = {
  cpu: cpus()[0]?.model ?? "unknown CPU",
  os: `${osName()} (${arch()})`,
  node: version("node", ["--version"]),
  clang: version(process.env["CHAD_CLANG"] ?? "clang", ["--version"]),
  rustc: version("rustc", ["--version"]),
  date: new Date().toISOString().slice(0, 10),
};

const rows = data.results.map((r) => {
  if (r.timings === null) return `| \`${r.name}\` | ${r.note ?? "no result"} | | | |`;
  const t = (label: string): number | undefined => r.timings!.find((x) => x.label === label)?.ms;
  const chad = t("chad");
  const node = t("node");
  const rust = t("rust");
  const vsNode = chad !== undefined && node !== undefined ? `${(node / chad).toFixed(2)}x` : "";
  return `| \`${r.name}\` | ${chad === undefined ? "" : fmt(chad)} | ${node === undefined ? "" : fmt(node)} | ${rust === undefined ? "" : fmt(rust)} | ${vsNode} |`;
});

const md = `<!-- GENERATED by docs/scripts/bench-page.ts. Do not edit; rerun the script. -->

Measured ${machine.date} on ${machine.cpu}, ${machine.os}. Node ${machine.node}, ${machine.clang}, ${machine.rustc}.
Best of ${data.runs} runs, wall clock including process startup. "vs Node" is Node's time divided by ChadScript's (above 1 means ChadScript is faster).

| Benchmark | ChadScript | Node | Rust | vs Node |
| --------- | ---------- | ---- | ---- | ------- |
${rows.join("\n")}
`;

writeFileSync(join(repo, "docs", "generated", "benchmarks.md"), md);
writeFileSync(
  join(repo, "docs", "generated", "benchmarks.json"),
  JSON.stringify({ machine, runs: data.runs, results: data.results }, null, 2) + "\n",
);
console.log("wrote docs/generated/benchmarks.{md,json}");
