// Generates docs/SUBSET.md — the single source of truth for the accepted TypeScript subset and
// the rejection codes — DIRECTLY from the validator's data (allowlists + code table), so the doc
// can never drift from what the compiler actually accepts. `bun run scripts/gen-subset.ts` rewrites
// the file; a unit test asserts the checked-in copy matches this output.

import ts from "typescript";
import { writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import {
  ALLOWED_KINDS,
  SUPPORTED_BINARY_OPS,
  SUPPORTED_UNARY_OPS,
} from "../src/validate/validate.js";
import {
  STRING_METHODS,
  ARRAY_METHODS,
  COLLECTION_METHODS,
  NAMESPACE_STATIC_ALLOW,
} from "../src/validate/rules.js";
import { CODE } from "../src/validate/codes.js";

const kindNames = (set: ReadonlySet<ts.SyntaxKind>): string[] =>
  [...set].map((k) => ts.SyntaxKind[k]).sort();

const opNames = (set: ReadonlySet<ts.SyntaxKind>): string[] =>
  [...set].map((k) => ts.tokenToString(k) ?? ts.SyntaxKind[k]).sort();

const list = (items: readonly string[]): string => items.map((i) => `- \`${i}\``).join("\n");

export function generateSubsetMarkdown(): string {
  const codeRows = Object.entries(CODE)
    .sort((a, b) => a[1].localeCompare(b[1]))
    .map(([name, code]) => `| \`${code}\` | ${name} |`)
    .join("\n");

  const namespaceRows = Object.entries(NAMESPACE_STATIC_ALLOW)
    .sort()
    .map(([ns, methods]) => {
      const ms = [...methods].sort();
      return `- \`${ns}\`: ${ms.length ? ms.map((m) => `\`${m}\``).join(", ") : "_(none)_"}`;
    })
    .join("\n");

  return `<!-- GENERATED by scripts/gen-subset.ts — DO NOT EDIT. Run \`bun run scripts/gen-subset.ts\`. -->
# ChadScript accepted subset

The set of TypeScript this compiler accepts, generated from the validator's allowlists and rejection
codes. Anything outside this subset is rejected at compile time (default-DENY) with a \`CS####\`
diagnostic — there is no "compiles but behaves differently than Node" third category.

## Accepted syntax (AST node kinds)

${list(kindNames(ALLOWED_KINDS))}

## Supported binary operators

${list(opNames(SUPPORTED_BINARY_OPS))}

## Supported unary operators

${list(opNames(SUPPORTED_UNARY_OPS))}

## Supported string methods

${list([...STRING_METHODS].sort())}

## Supported array methods

${list([...ARRAY_METHODS].sort())}

## Supported Map methods

${list([...COLLECTION_METHODS.map].sort())}

## Supported Set methods

${list([...COLLECTION_METHODS.set].sort())}

## Supported namespace statics

${namespaceRows}

## Rejection codes

| Code | Rule |
| ---- | ---- |
${codeRows}
`;
}

// Run directly → (re)write the doc.
const isMain = process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1];
if (isMain) {
  const out = join(dirname(fileURLToPath(import.meta.url)), "..", "docs", "SUBSET.md");
  writeFileSync(out, generateSubsetMarkdown());
  console.log(`wrote ${out}`);
}
