export class PromiseGenerator {
  generateDeclarations(): string {
    let ir = '; Promise type declarations\n';
    ir += '; State machine: 0 = pending, 1 = fulfilled, 2 = rejected\n\n';

    ir += '; Callback node for .then()/.catch() chains\n';
    ir += '; { next: %PromiseCallback*, onFulfilled: void (i8*, i8*)*, onRejected: void (i8*, i8*)*, childPromise: %Promise*, context: i8* }\n';
    ir += '%PromiseCallback = type { %PromiseCallback*, void (i8*, i8*)*, void (i8*, i8*)*, %Promise*, i8* }\n\n';

    ir += '; Promise struct: { state: i32, value: i8*, callbacks: %PromiseCallback* }\n';
    ir += '%Promise = type { i32, i8*, %PromiseCallback* }\n\n';

    ir += '; PromiseAllState: { counter: i32*, results: %Array*, result_promise: %Promise*, total: i32, rejected: i32* }\n';
    ir += '%PromiseAllState = type { i32*, %Array*, %Promise*, i32, i32* }\n\n';

    ir += '; PromiseAllContext: { state: %PromiseAllState*, index: i32 }\n';
    ir += '%PromiseAllContext = type { %PromiseAllState*, i32 }\n\n';

    return ir;
  }

  generatePromiseNew(): string {
    let ir = '; __Promise_new() -> %Promise*\n';
    ir += '; Creates a new pending promise\n';
    ir += 'define %Promise* @__Promise_new() {\n';
    ir += 'entry:\n';
    ir += '  %mem = call i8* @GC_malloc(i64 24)\n';
    ir += '  %promise = bitcast i8* %mem to %Promise*\n';
    ir += '  ; Initialize state = 0 (pending)\n';
    ir += '  %state_ptr = getelementptr inbounds %Promise, %Promise* %promise, i32 0, i32 0\n';
    ir += '  store i32 0, i32* %state_ptr\n';
    ir += '  ; Initialize value = null\n';
    ir += '  %value_ptr = getelementptr inbounds %Promise, %Promise* %promise, i32 0, i32 1\n';
    ir += '  store i8* null, i8** %value_ptr\n';
    ir += '  ; Initialize callbacks = null\n';
    ir += '  %callbacks_ptr = getelementptr inbounds %Promise, %Promise* %promise, i32 0, i32 2\n';
    ir += '  store %PromiseCallback* null, %PromiseCallback** %callbacks_ptr\n';
    ir += '  ret %Promise* %promise\n';
    ir += '}\n\n';
    return ir;
  }

  generatePromiseResolve(): string {
    let ir = '; __Promise_resolve(%Promise* promise, i8* value)\n';
    ir += '; Resolves a promise with the given value and runs all callbacks\n';
    ir += 'define void @__Promise_resolve(%Promise* %promise, i8* %value) {\n';
    ir += 'entry:\n';
    ir += '  ; Check if already settled\n';
    ir += '  %state_ptr = getelementptr inbounds %Promise, %Promise* %promise, i32 0, i32 0\n';
    ir += '  %state = load i32, i32* %state_ptr\n';
    ir += '  %is_pending = icmp eq i32 %state, 0\n';
    ir += '  br i1 %is_pending, label %do_resolve, label %done\n';
    ir += '\n';
    ir += 'do_resolve:\n';
    ir += '  ; Set state = 1 (fulfilled)\n';
    ir += '  store i32 1, i32* %state_ptr\n';
    ir += '  ; Set value\n';
    ir += '  %value_ptr = getelementptr inbounds %Promise, %Promise* %promise, i32 0, i32 1\n';
    ir += '  store i8* %value, i8** %value_ptr\n';
    ir += '  ; Run callbacks\n';
    ir += '  call void @__Promise_runCallbacks(%Promise* %promise)\n';
    ir += '  br label %done\n';
    ir += '\n';
    ir += 'done:\n';
    ir += '  ret void\n';
    ir += '}\n\n';
    return ir;
  }

  generatePromiseReject(): string {
    let ir = '; __Promise_reject(%Promise* promise, i8* reason)\n';
    ir += '; Rejects a promise with the given reason and runs all callbacks\n';
    ir += 'define void @__Promise_reject(%Promise* %promise, i8* %reason) {\n';
    ir += 'entry:\n';
    ir += '  ; Check if already settled\n';
    ir += '  %state_ptr = getelementptr inbounds %Promise, %Promise* %promise, i32 0, i32 0\n';
    ir += '  %state = load i32, i32* %state_ptr\n';
    ir += '  %is_pending = icmp eq i32 %state, 0\n';
    ir += '  br i1 %is_pending, label %do_reject, label %done\n';
    ir += '\n';
    ir += 'do_reject:\n';
    ir += '  ; Set state = 2 (rejected)\n';
    ir += '  store i32 2, i32* %state_ptr\n';
    ir += '  ; Set value (reason)\n';
    ir += '  %value_ptr = getelementptr inbounds %Promise, %Promise* %promise, i32 0, i32 1\n';
    ir += '  store i8* %reason, i8** %value_ptr\n';
    ir += '  ; Run callbacks\n';
    ir += '  call void @__Promise_runCallbacks(%Promise* %promise)\n';
    ir += '  br label %done\n';
    ir += '\n';
    ir += 'done:\n';
    ir += '  ret void\n';
    ir += '}\n\n';
    return ir;
  }

  generatePromiseRunCallbacks(): string {
    let ir = '; __Promise_runCallbacks(%Promise* promise)\n';
    ir += '; Runs all pending callbacks (onFulfilled or onRejected based on state)\n';
    ir += 'define void @__Promise_runCallbacks(%Promise* %promise) {\n';
    ir += 'entry:\n';
    ir += '  %state_ptr = getelementptr inbounds %Promise, %Promise* %promise, i32 0, i32 0\n';
    ir += '  %state = load i32, i32* %state_ptr\n';
    ir += '  %value_ptr = getelementptr inbounds %Promise, %Promise* %promise, i32 0, i32 1\n';
    ir += '  %value = load i8*, i8** %value_ptr\n';
    ir += '  %callbacks_ptr = getelementptr inbounds %Promise, %Promise* %promise, i32 0, i32 2\n';
    ir += '  %first_callback = load %PromiseCallback*, %PromiseCallback** %callbacks_ptr\n';
    ir += '  br label %loop\n';
    ir += '\n';
    ir += 'loop:\n';
    ir += '  %callback = phi %PromiseCallback* [ %first_callback, %entry ], [ %next, %continue ]\n';
    ir += '  %is_null = icmp eq %PromiseCallback* %callback, null\n';
    ir += '  br i1 %is_null, label %done, label %process\n';
    ir += '\n';
    ir += 'process:\n';
    ir += '  ; Load context pointer for this callback\n';
    ir += '  %context_ptr = getelementptr inbounds %PromiseCallback, %PromiseCallback* %callback, i32 0, i32 4\n';
    ir += '  %context = load i8*, i8** %context_ptr\n';
    ir += '  ; Check state to determine which callback to run\n';
    ir += '  %is_fulfilled = icmp eq i32 %state, 1\n';
    ir += '  br i1 %is_fulfilled, label %run_fulfilled, label %check_rejected\n';
    ir += '\n';
    ir += 'run_fulfilled:\n';
    ir += '  %on_fulfilled_ptr = getelementptr inbounds %PromiseCallback, %PromiseCallback* %callback, i32 0, i32 1\n';
    ir += '  %on_fulfilled = load void (i8*, i8*)*, void (i8*, i8*)** %on_fulfilled_ptr\n';
    ir += '  %has_on_fulfilled = icmp ne void (i8*, i8*)* %on_fulfilled, null\n';
    ir += '  br i1 %has_on_fulfilled, label %call_fulfilled, label %continue\n';
    ir += '\n';
    ir += 'call_fulfilled:\n';
    ir += '  call void %on_fulfilled(i8* %value, i8* %context)\n';
    ir += '  br label %continue\n';
    ir += '\n';
    ir += 'check_rejected:\n';
    ir += '  %is_rejected = icmp eq i32 %state, 2\n';
    ir += '  br i1 %is_rejected, label %run_rejected, label %continue\n';
    ir += '\n';
    ir += 'run_rejected:\n';
    ir += '  %on_rejected_ptr = getelementptr inbounds %PromiseCallback, %PromiseCallback* %callback, i32 0, i32 2\n';
    ir += '  %on_rejected = load void (i8*, i8*)*, void (i8*, i8*)** %on_rejected_ptr\n';
    ir += '  %has_on_rejected = icmp ne void (i8*, i8*)* %on_rejected, null\n';
    ir += '  br i1 %has_on_rejected, label %call_rejected, label %continue\n';
    ir += '\n';
    ir += 'call_rejected:\n';
    ir += '  call void %on_rejected(i8* %value, i8* %context)\n';
    ir += '  br label %continue\n';
    ir += '\n';
    ir += 'continue:\n';
    ir += '  %next_ptr = getelementptr inbounds %PromiseCallback, %PromiseCallback* %callback, i32 0, i32 0\n';
    ir += '  %next = load %PromiseCallback*, %PromiseCallback** %next_ptr\n';
    ir += '  br label %loop\n';
    ir += '\n';
    ir += 'done:\n';
    ir += '  ; Clear callbacks after running\n';
    ir += '  store %PromiseCallback* null, %PromiseCallback** %callbacks_ptr\n';
    ir += '  ret void\n';
    ir += '}\n\n';
    return ir;
  }

  generatePromiseThen(): string {
    let ir = '; __Promise_then(%Promise* promise, void (i8*, i8*)* onFulfilled, void (i8*, i8*)* onRejected) -> %Promise*\n';
    ir += '; Adds callbacks and returns a new promise for chaining\n';
    ir += 'define %Promise* @__Promise_then(%Promise* %promise, void (i8*, i8*)* %onFulfilled, void (i8*, i8*)* %onRejected) {\n';
    ir += 'entry:\n';
    ir += '  ; Create child promise\n';
    ir += '  %child = call %Promise* @__Promise_new()\n';
    ir += '\n';
    ir += '  ; Allocate callback node (40 bytes: 5 pointers)\n';
    ir += '  %cb_mem = call i8* @GC_malloc(i64 40)\n';
    ir += '  %cb = bitcast i8* %cb_mem to %PromiseCallback*\n';
    ir += '\n';
    ir += '  ; Initialize callback node\n';
    ir += '  %cb_next_ptr = getelementptr inbounds %PromiseCallback, %PromiseCallback* %cb, i32 0, i32 0\n';
    ir += '  store %PromiseCallback* null, %PromiseCallback** %cb_next_ptr\n';
    ir += '  %cb_fulfilled_ptr = getelementptr inbounds %PromiseCallback, %PromiseCallback* %cb, i32 0, i32 1\n';
    ir += '  store void (i8*, i8*)* %onFulfilled, void (i8*, i8*)** %cb_fulfilled_ptr\n';
    ir += '  %cb_rejected_ptr = getelementptr inbounds %PromiseCallback, %PromiseCallback* %cb, i32 0, i32 2\n';
    ir += '  store void (i8*, i8*)* %onRejected, void (i8*, i8*)** %cb_rejected_ptr\n';
    ir += '  %cb_child_ptr = getelementptr inbounds %PromiseCallback, %PromiseCallback* %cb, i32 0, i32 3\n';
    ir += '  store %Promise* %child, %Promise** %cb_child_ptr\n';
    ir += '  ; Initialize context to null (for standard .then calls)\n';
    ir += '  %cb_context_ptr = getelementptr inbounds %PromiseCallback, %PromiseCallback* %cb, i32 0, i32 4\n';
    ir += '  store i8* null, i8** %cb_context_ptr\n';
    ir += '\n';
    ir += '  ; Check if promise is already settled\n';
    ir += '  %state_ptr = getelementptr inbounds %Promise, %Promise* %promise, i32 0, i32 0\n';
    ir += '  %state = load i32, i32* %state_ptr\n';
    ir += '  %is_pending = icmp eq i32 %state, 0\n';
    ir += '  br i1 %is_pending, label %add_callback, label %run_immediately\n';
    ir += '\n';
    ir += 'add_callback:\n';
    ir += '  ; Promise is pending, add to callback list\n';
    ir += '  %callbacks_ptr = getelementptr inbounds %Promise, %Promise* %promise, i32 0, i32 2\n';
    ir += '  %existing = load %PromiseCallback*, %PromiseCallback** %callbacks_ptr\n';
    ir += '  store %PromiseCallback* %cb_next_ptr, %PromiseCallback** %cb_next_ptr\n';
    ir += '  ; Append to end of list (simplified: prepend)\n';
    ir += '  store %PromiseCallback* %existing, %PromiseCallback** %cb_next_ptr\n';
    ir += '  store %PromiseCallback* %cb, %PromiseCallback** %callbacks_ptr\n';
    ir += '  br label %done\n';
    ir += '\n';
    ir += 'run_immediately:\n';
    ir += '  ; Promise already settled, run callback immediately\n';
    ir += '  %value_ptr = getelementptr inbounds %Promise, %Promise* %promise, i32 0, i32 1\n';
    ir += '  %value = load i8*, i8** %value_ptr\n';
    ir += '  %is_fulfilled = icmp eq i32 %state, 1\n';
    ir += '  br i1 %is_fulfilled, label %call_fulfilled, label %call_rejected\n';
    ir += '\n';
    ir += 'call_fulfilled:\n';
    ir += '  %has_fulfilled = icmp ne void (i8*, i8*)* %onFulfilled, null\n';
    ir += '  br i1 %has_fulfilled, label %do_call_fulfilled, label %done\n';
    ir += '\n';
    ir += 'do_call_fulfilled:\n';
    ir += '  call void %onFulfilled(i8* %value, i8* null)\n';
    ir += '  br label %done\n';
    ir += '\n';
    ir += 'call_rejected:\n';
    ir += '  %has_rejected = icmp ne void (i8*, i8*)* %onRejected, null\n';
    ir += '  br i1 %has_rejected, label %do_call_rejected, label %done\n';
    ir += '\n';
    ir += 'do_call_rejected:\n';
    ir += '  call void %onRejected(i8* %value, i8* null)\n';
    ir += '  br label %done\n';
    ir += '\n';
    ir += 'done:\n';
    ir += '  ret %Promise* %child\n';
    ir += '}\n\n';
    return ir;
  }

  generatePromiseThenWithContext(): string {
    let ir = '; __Promise_then_with_context(%Promise* promise, void (i8*, i8*)* onFulfilled, void (i8*, i8*)* onRejected, i8* context) -> %Promise*\n';
    ir += '; Adds callbacks with context and returns a new promise for chaining\n';
    ir += 'define %Promise* @__Promise_then_with_context(%Promise* %promise, void (i8*, i8*)* %onFulfilled, void (i8*, i8*)* %onRejected, i8* %context) {\n';
    ir += 'entry:\n';
    ir += '  ; Create child promise\n';
    ir += '  %child = call %Promise* @__Promise_new()\n';
    ir += '\n';
    ir += '  ; Allocate callback node (40 bytes: 5 pointers)\n';
    ir += '  %cb_mem = call i8* @GC_malloc(i64 40)\n';
    ir += '  %cb = bitcast i8* %cb_mem to %PromiseCallback*\n';
    ir += '\n';
    ir += '  ; Initialize callback node\n';
    ir += '  %cb_next_ptr = getelementptr inbounds %PromiseCallback, %PromiseCallback* %cb, i32 0, i32 0\n';
    ir += '  store %PromiseCallback* null, %PromiseCallback** %cb_next_ptr\n';
    ir += '  %cb_fulfilled_ptr = getelementptr inbounds %PromiseCallback, %PromiseCallback* %cb, i32 0, i32 1\n';
    ir += '  store void (i8*, i8*)* %onFulfilled, void (i8*, i8*)** %cb_fulfilled_ptr\n';
    ir += '  %cb_rejected_ptr = getelementptr inbounds %PromiseCallback, %PromiseCallback* %cb, i32 0, i32 2\n';
    ir += '  store void (i8*, i8*)* %onRejected, void (i8*, i8*)** %cb_rejected_ptr\n';
    ir += '  %cb_child_ptr = getelementptr inbounds %PromiseCallback, %PromiseCallback* %cb, i32 0, i32 3\n';
    ir += '  store %Promise* %child, %Promise** %cb_child_ptr\n';
    ir += '  ; Store the context\n';
    ir += '  %cb_context_ptr = getelementptr inbounds %PromiseCallback, %PromiseCallback* %cb, i32 0, i32 4\n';
    ir += '  store i8* %context, i8** %cb_context_ptr\n';
    ir += '\n';
    ir += '  ; Check if promise is already settled\n';
    ir += '  %state_ptr = getelementptr inbounds %Promise, %Promise* %promise, i32 0, i32 0\n';
    ir += '  %state = load i32, i32* %state_ptr\n';
    ir += '  %is_pending = icmp eq i32 %state, 0\n';
    ir += '  br i1 %is_pending, label %add_callback, label %run_immediately\n';
    ir += '\n';
    ir += 'add_callback:\n';
    ir += '  ; Promise is pending, add to callback list\n';
    ir += '  %callbacks_ptr = getelementptr inbounds %Promise, %Promise* %promise, i32 0, i32 2\n';
    ir += '  %existing = load %PromiseCallback*, %PromiseCallback** %callbacks_ptr\n';
    ir += '  store %PromiseCallback* %existing, %PromiseCallback** %cb_next_ptr\n';
    ir += '  store %PromiseCallback* %cb, %PromiseCallback** %callbacks_ptr\n';
    ir += '  br label %done\n';
    ir += '\n';
    ir += 'run_immediately:\n';
    ir += '  ; Promise already settled, run callback immediately with context\n';
    ir += '  %value_ptr = getelementptr inbounds %Promise, %Promise* %promise, i32 0, i32 1\n';
    ir += '  %value = load i8*, i8** %value_ptr\n';
    ir += '  %is_fulfilled = icmp eq i32 %state, 1\n';
    ir += '  br i1 %is_fulfilled, label %call_fulfilled, label %call_rejected\n';
    ir += '\n';
    ir += 'call_fulfilled:\n';
    ir += '  %has_fulfilled = icmp ne void (i8*, i8*)* %onFulfilled, null\n';
    ir += '  br i1 %has_fulfilled, label %do_call_fulfilled, label %done\n';
    ir += '\n';
    ir += 'do_call_fulfilled:\n';
    ir += '  call void %onFulfilled(i8* %value, i8* %context)\n';
    ir += '  br label %done\n';
    ir += '\n';
    ir += 'call_rejected:\n';
    ir += '  %has_rejected = icmp ne void (i8*, i8*)* %onRejected, null\n';
    ir += '  br i1 %has_rejected, label %do_call_rejected, label %done\n';
    ir += '\n';
    ir += 'do_call_rejected:\n';
    ir += '  call void %onRejected(i8* %value, i8* %context)\n';
    ir += '  br label %done\n';
    ir += '\n';
    ir += 'done:\n';
    ir += '  ret %Promise* %child\n';
    ir += '}\n\n';
    return ir;
  }

  generatePromiseResolveStatic(): string {
    let ir = '; __Promise_resolve_static(i8* value) -> %Promise*\n';
    ir += '; Creates an already-resolved promise (Promise.resolve(value))\n';
    ir += 'define %Promise* @__Promise_resolve_static(i8* %value) {\n';
    ir += 'entry:\n';
    ir += '  %promise = call %Promise* @__Promise_new()\n';
    ir += '  call void @__Promise_resolve(%Promise* %promise, i8* %value)\n';
    ir += '  ret %Promise* %promise\n';
    ir += '}\n\n';
    return ir;
  }

  generatePromiseRejectStatic(): string {
    let ir = '; __Promise_reject_static(i8* reason) -> %Promise*\n';
    ir += '; Creates an already-rejected promise (Promise.reject(reason))\n';
    ir += 'define %Promise* @__Promise_reject_static(i8* %reason) {\n';
    ir += 'entry:\n';
    ir += '  %promise = call %Promise* @__Promise_new()\n';
    ir += '  call void @__Promise_reject(%Promise* %promise, i8* %reason)\n';
    ir += '  ret %Promise* %promise\n';
    ir += '}\n\n';
    return ir;
  }

  generatePromiseAllCallbacks(): string {
    let ir = '';

    ir += '; __Promise_all_onFulfilled(i8* value, i8* context)\n';
    ir += '; Callback for Promise.all - stores result and decrements counter\n';
    ir += 'define void @__Promise_all_onFulfilled(i8* %value, i8* %context) {\n';
    ir += 'entry:\n';
    ir += '  ; Cast context to PromiseAllContext\n';
    ir += '  %ctx = bitcast i8* %context to %PromiseAllContext*\n';
    ir += '\n';
    ir += '  ; Get state pointer from context\n';
    ir += '  %state_ptr_ptr = getelementptr inbounds %PromiseAllContext, %PromiseAllContext* %ctx, i32 0, i32 0\n';
    ir += '  %state = load %PromiseAllState*, %PromiseAllState** %state_ptr_ptr\n';
    ir += '\n';
    ir += '  ; Get index from context\n';
    ir += '  %index_ptr = getelementptr inbounds %PromiseAllContext, %PromiseAllContext* %ctx, i32 0, i32 1\n';
    ir += '  %index = load i32, i32* %index_ptr\n';
    ir += '\n';
    ir += '  ; Check if already rejected\n';
    ir += '  %rejected_ptr_ptr = getelementptr inbounds %PromiseAllState, %PromiseAllState* %state, i32 0, i32 4\n';
    ir += '  %rejected_ptr = load i32*, i32** %rejected_ptr_ptr\n';
    ir += '  %rejected = load i32, i32* %rejected_ptr\n';
    ir += '  %is_rejected = icmp ne i32 %rejected, 0\n';
    ir += '  br i1 %is_rejected, label %done, label %store_result\n';
    ir += '\n';
    ir += 'store_result:\n';
    ir += '  ; Get results array from state\n';
    ir += '  %results_ptr_ptr = getelementptr inbounds %PromiseAllState, %PromiseAllState* %state, i32 0, i32 1\n';
    ir += '  %results = load %Array*, %Array** %results_ptr_ptr\n';
    ir += '\n';
    ir += '  ; Store value at index in results array data\n';
    ir += '  %data_ptr_ptr = getelementptr inbounds %Array, %Array* %results, i32 0, i32 2\n';
    ir += '  %data_ptr = load double*, double** %data_ptr_ptr\n';
    ir += '  %data_i8 = bitcast double* %data_ptr to i8**\n';
    ir += '  %slot = getelementptr inbounds i8*, i8** %data_i8, i32 %index\n';
    ir += '  store i8* %value, i8** %slot\n';
    ir += '\n';
    ir += '  ; Decrement counter\n';
    ir += '  %counter_ptr_ptr = getelementptr inbounds %PromiseAllState, %PromiseAllState* %state, i32 0, i32 0\n';
    ir += '  %counter_ptr = load i32*, i32** %counter_ptr_ptr\n';
    ir += '  %counter = load i32, i32* %counter_ptr\n';
    ir += '  %new_counter = sub i32 %counter, 1\n';
    ir += '  store i32 %new_counter, i32* %counter_ptr\n';
    ir += '\n';
    ir += '  ; Check if all done\n';
    ir += '  %all_done = icmp eq i32 %new_counter, 0\n';
    ir += '  br i1 %all_done, label %resolve_all, label %done\n';
    ir += '\n';
    ir += 'resolve_all:\n';
    ir += '  ; Get result promise from state\n';
    ir += '  %result_promise_ptr = getelementptr inbounds %PromiseAllState, %PromiseAllState* %state, i32 0, i32 2\n';
    ir += '  %result_promise = load %Promise*, %Promise** %result_promise_ptr\n';
    ir += '  ; Resolve with results array\n';
    ir += '  %results_i8 = bitcast %Array* %results to i8*\n';
    ir += '  call void @__Promise_resolve(%Promise* %result_promise, i8* %results_i8)\n';
    ir += '  br label %done\n';
    ir += '\n';
    ir += 'done:\n';
    ir += '  ret void\n';
    ir += '}\n\n';

    ir += '; __Promise_all_onRejected(i8* reason, i8* context)\n';
    ir += '; Callback for Promise.all - rejects the result promise on first rejection\n';
    ir += 'define void @__Promise_all_onRejected(i8* %reason, i8* %context) {\n';
    ir += 'entry:\n';
    ir += '  ; Cast context to PromiseAllContext\n';
    ir += '  %ctx = bitcast i8* %context to %PromiseAllContext*\n';
    ir += '\n';
    ir += '  ; Get state pointer from context\n';
    ir += '  %state_ptr_ptr = getelementptr inbounds %PromiseAllContext, %PromiseAllContext* %ctx, i32 0, i32 0\n';
    ir += '  %state = load %PromiseAllState*, %PromiseAllState** %state_ptr_ptr\n';
    ir += '\n';
    ir += '  ; Check if already rejected (first one wins)\n';
    ir += '  %rejected_ptr_ptr = getelementptr inbounds %PromiseAllState, %PromiseAllState* %state, i32 0, i32 4\n';
    ir += '  %rejected_ptr = load i32*, i32** %rejected_ptr_ptr\n';
    ir += '  %rejected = load i32, i32* %rejected_ptr\n';
    ir += '  %already_rejected = icmp ne i32 %rejected, 0\n';
    ir += '  br i1 %already_rejected, label %done, label %do_reject\n';
    ir += '\n';
    ir += 'do_reject:\n';
    ir += '  ; Mark as rejected\n';
    ir += '  store i32 1, i32* %rejected_ptr\n';
    ir += '\n';
    ir += '  ; Get result promise from state and reject it\n';
    ir += '  %result_promise_ptr = getelementptr inbounds %PromiseAllState, %PromiseAllState* %state, i32 0, i32 2\n';
    ir += '  %result_promise = load %Promise*, %Promise** %result_promise_ptr\n';
    ir += '  call void @__Promise_reject(%Promise* %result_promise, i8* %reason)\n';
    ir += '  br label %done\n';
    ir += '\n';
    ir += 'done:\n';
    ir += '  ret void\n';
    ir += '}\n\n';

    return ir;
  }

  generatePromiseAll(): string {
    let ir = '; __Promise_all(%Array* promises) -> %Promise*\n';
    ir += '; Returns a promise that resolves when all input promises resolve\n';
    ir += '; The resolved value is an array of results\n';
    ir += 'define %Promise* @__Promise_all(%Array* %promises) {\n';
    ir += 'entry:\n';
    ir += '  ; Create result promise\n';
    ir += '  %result_promise = call %Promise* @__Promise_new()\n';
    ir += '\n';
    ir += '  ; Get array length\n';
    ir += '  %len_ptr = getelementptr inbounds %Array, %Array* %promises, i32 0, i32 0\n';
    ir += '  %len_double = load double, double* %len_ptr\n';
    ir += '  %len = fptosi double %len_double to i32\n';
    ir += '\n';
    ir += '  ; Check if empty array\n';
    ir += '  %is_empty = icmp eq i32 %len, 0\n';
    ir += '  br i1 %is_empty, label %resolve_empty, label %setup_state\n';
    ir += '\n';
    ir += 'resolve_empty:\n';
    ir += '  ; Resolve with empty array\n';
    ir += '  %empty_arr_mem = call i8* @GC_malloc(i64 24)\n';
    ir += '  %empty_arr = bitcast i8* %empty_arr_mem to %Array*\n';
    ir += '  %empty_len_ptr = getelementptr inbounds %Array, %Array* %empty_arr, i32 0, i32 0\n';
    ir += '  store double 0.0, double* %empty_len_ptr\n';
    ir += '  %empty_cap_ptr = getelementptr inbounds %Array, %Array* %empty_arr, i32 0, i32 1\n';
    ir += '  store double 0.0, double* %empty_cap_ptr\n';
    ir += '  %empty_data_ptr = getelementptr inbounds %Array, %Array* %empty_arr, i32 0, i32 2\n';
    ir += '  store double* null, double** %empty_data_ptr\n';
    ir += '  %empty_ptr = bitcast %Array* %empty_arr to i8*\n';
    ir += '  call void @__Promise_resolve(%Promise* %result_promise, i8* %empty_ptr)\n';
    ir += '  br label %done\n';
    ir += '\n';
    ir += 'setup_state:\n';
    ir += '  ; Allocate PromiseAllState (40 bytes: 5 fields)\n';
    ir += '  %state_mem = call i8* @GC_malloc(i64 40)\n';
    ir += '  %state = bitcast i8* %state_mem to %PromiseAllState*\n';
    ir += '\n';
    ir += '  ; Allocate counter\n';
    ir += '  %counter_mem = call i8* @GC_malloc(i64 4)\n';
    ir += '  %counter = bitcast i8* %counter_mem to i32*\n';
    ir += '  store i32 %len, i32* %counter\n';
    ir += '\n';
    ir += '  ; Allocate rejected flag\n';
    ir += '  %rejected_mem = call i8* @GC_malloc(i64 4)\n';
    ir += '  %rejected = bitcast i8* %rejected_mem to i32*\n';
    ir += '  store i32 0, i32* %rejected\n';
    ir += '\n';
    ir += '  ; Allocate results array\n';
    ir += '  %results_arr_mem = call i8* @GC_malloc(i64 24)\n';
    ir += '  %results_arr = bitcast i8* %results_arr_mem to %Array*\n';
    ir += '  %results_len_ptr = getelementptr inbounds %Array, %Array* %results_arr, i32 0, i32 0\n';
    ir += '  store double %len_double, double* %results_len_ptr\n';
    ir += '  %results_cap_ptr = getelementptr inbounds %Array, %Array* %results_arr, i32 0, i32 1\n';
    ir += '  store double %len_double, double* %results_cap_ptr\n';
    ir += '  %results_data_size = mul i32 %len, 8\n';
    ir += '  %results_data_size_i64 = sext i32 %results_data_size to i64\n';
    ir += '  %results_data_mem = call i8* @GC_malloc(i64 %results_data_size_i64)\n';
    ir += '  %results_data = bitcast i8* %results_data_mem to double*\n';
    ir += '  %results_data_ptr = getelementptr inbounds %Array, %Array* %results_arr, i32 0, i32 2\n';
    ir += '  store double* %results_data, double** %results_data_ptr\n';
    ir += '\n';
    ir += '  ; Initialize PromiseAllState fields\n';
    ir += '  %state_counter_ptr = getelementptr inbounds %PromiseAllState, %PromiseAllState* %state, i32 0, i32 0\n';
    ir += '  store i32* %counter, i32** %state_counter_ptr\n';
    ir += '  %state_results_ptr = getelementptr inbounds %PromiseAllState, %PromiseAllState* %state, i32 0, i32 1\n';
    ir += '  store %Array* %results_arr, %Array** %state_results_ptr\n';
    ir += '  %state_promise_ptr = getelementptr inbounds %PromiseAllState, %PromiseAllState* %state, i32 0, i32 2\n';
    ir += '  store %Promise* %result_promise, %Promise** %state_promise_ptr\n';
    ir += '  %state_total_ptr = getelementptr inbounds %PromiseAllState, %PromiseAllState* %state, i32 0, i32 3\n';
    ir += '  store i32 %len, i32* %state_total_ptr\n';
    ir += '  %state_rejected_ptr = getelementptr inbounds %PromiseAllState, %PromiseAllState* %state, i32 0, i32 4\n';
    ir += '  store i32* %rejected, i32** %state_rejected_ptr\n';
    ir += '\n';
    ir += '  ; Get promises array data pointer\n';
    ir += '  %promises_data_ptr_ptr = getelementptr inbounds %Array, %Array* %promises, i32 0, i32 2\n';
    ir += '  %promises_data_ptr = load double*, double** %promises_data_ptr_ptr\n';
    ir += '  %promises_data = bitcast double* %promises_data_ptr to %Promise**\n';
    ir += '\n';
    ir += '  ; Loop through promises and set up callbacks\n';
    ir += '  br label %loop\n';
    ir += '\n';
    ir += 'loop:\n';
    ir += '  %i = phi i32 [ 0, %setup_state ], [ %next_i, %loop_body ]\n';
    ir += '  %loop_done = icmp sge i32 %i, %len\n';
    ir += '  br i1 %loop_done, label %done, label %loop_body\n';
    ir += '\n';
    ir += 'loop_body:\n';
    ir += '  ; Get promise at index i\n';
    ir += '  %promise_slot = getelementptr inbounds %Promise*, %Promise** %promises_data, i32 %i\n';
    ir += '  %promise = load %Promise*, %Promise** %promise_slot\n';
    ir += '\n';
    ir += '  ; Allocate PromiseAllContext for this index (16 bytes: pointer + i32)\n';
    ir += '  %ctx_mem = call i8* @GC_malloc(i64 16)\n';
    ir += '  %ctx = bitcast i8* %ctx_mem to %PromiseAllContext*\n';
    ir += '  %ctx_state_ptr = getelementptr inbounds %PromiseAllContext, %PromiseAllContext* %ctx, i32 0, i32 0\n';
    ir += '  store %PromiseAllState* %state, %PromiseAllState** %ctx_state_ptr\n';
    ir += '  %ctx_index_ptr = getelementptr inbounds %PromiseAllContext, %PromiseAllContext* %ctx, i32 0, i32 1\n';
    ir += '  store i32 %i, i32* %ctx_index_ptr\n';
    ir += '  %ctx_i8 = bitcast %PromiseAllContext* %ctx to i8*\n';
    ir += '\n';
    ir += '  ; Register callbacks with context\n';
    ir += '  call %Promise* @__Promise_then_with_context(%Promise* %promise, void (i8*, i8*)* @__Promise_all_onFulfilled, void (i8*, i8*)* @__Promise_all_onRejected, i8* %ctx_i8)\n';
    ir += '\n';
    ir += '  %next_i = add i32 %i, 1\n';
    ir += '  br label %loop\n';
    ir += '\n';
    ir += 'done:\n';
    ir += '  ret %Promise* %result_promise\n';
    ir += '}\n\n';
    return ir;
  }

  generateAll(): string {
    let ir = '';
    ir += this.generatePromiseNew();
    ir += this.generatePromiseResolve();
    ir += this.generatePromiseReject();
    ir += this.generatePromiseRunCallbacks();
    ir += this.generatePromiseThen();
    ir += this.generatePromiseThenWithContext();
    ir += this.generatePromiseResolveStatic();
    ir += this.generatePromiseRejectStatic();
    ir += this.generatePromiseAllCallbacks();
    ir += this.generatePromiseAll();
    return ir;
  }
}
